### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by LayanJethwa** [Valokoodari/btd6-ahk#39]
Please could we have support for no monkey knowledge, as not many people using this script will have full monkey knowledge, as many would use this script to grind to get full monkey knowledge.

It would also be helpful if the script used simpler strategies, such as ones showcased by FenixKillah on YouTube, where you can go AFK after 15 rounds, this would leave less room for errors with timings.

Timings are quite an issue for me personally, as I cannot find the right timescale to work just right, to remedy this, maybe consider looking at the round numbers to see when to place and upgrade? It would also be useful to have a tool to determine the correct timescale based on frame rate.

Also, dark castle coords and placements seem to be broken, not sure why.

Finally, would it be possible to add a feature whereby if you have been consistently losing on a map, say, twice in a row, it just does dark castle runs or something, so you still get points for the collection, although it is less, but you're not just constantly losing and not getting anything, and then maybe the map that you lost on could be flagged? This would definitely be a lot more helpful for overnight AFK sessions for example.

I understand how hard it is to code hotkeys, so I understand if these features are too hard to implement. The script is great as it is, thank you for putting in all this work!

**Comment by Valokoodari** [comment]
### Todo
- [ ] No monkey knowledge required to allow new players to use the script
- [ ] Simpler strategies for more stability
- [ ] Defeat streak counter and fail-safe strategy

**Comment by valen214** [comment]
One more thing on the (2) point, I'm not certain if the function keeps the reference to `monkeys` so it reflects update. It's most likely so but it's not impossible that AHK cloned the variable on preprocessing stage

**Comment by valen214** [comment]
4. I'd love to see if we could make the map script played standalone like this https://www.autohotkey.com/boards/viewtopic.php?t=71960

**Comment by Valokoodari** [comment]
Thank you @valen214 for all these suggestions.

> 1. Does it sound crazy to implement auto update kek.  

For the time being I don't really see a reason to spend the time to implement and test auto update. But maybe in the future if there's extra time with no better use.


> 2. –– found the current util functions api a bit annoying, I'm trying to wrap them this way, so I don't need to type in the coordinates each time. With this format I think it's a bit easier to build the map script.

I did think about putting the towers coordinates in a map like that but thought that it would be better for now to use the same style for every map as Sanctuary has moving platforms. Maybe the best solution would be to create functions that also calculate the coordinates of moving platforms based on the round number.


> 3. adding new map script need to modify two files `utils/globals.ahk(4): maps` and `maps/_include.ahk`. I know it's picky but I think that is a bit troublesome too, I'm searching if there's any ahk mechanisms to avoid such process.

It should be possible to automatically include every file in a directory but the current solution seemed to be a lot cleaner than the methods I came upon. But yeah, it's annoying to modify multiple files because of a single change.


> 4. I'd love to see if we could make the map script played standalone ––

I dropped the standalone map script support when collection events stopped counting the collectables from games started with the old freeplay -> restart method. But it's possible to bring that back even though it won't really work with collection events. Wouldn't be a bad idea to check that monkey money can still be earned that way though. It's also possible that even the collectables can be gained this way again as I haven't tested it in a long time.
