### ISSUE TITLE
Wrong button for bottom path upgrade

### ISSUE THREAD

**Issue by MichaelKoopa** [Valokoodari/btd6-ahk#4]
The default in-game hotkey for the bottom path upgrade is set to slash and in the script it presses minus, so you either have to switch the hotkey in-game or in the script for it to work correctly. Other than that one problem it has been working perfectly.
![image](https://user-images.githubusercontent.com/16768022/120891541-c4c34b00-c5ce-11eb-9e31-ceeab0bb2b57.png)

**Comment by Valokoodari** [comment]
Thanks for letting me know. I'll check tomorrow if I can detect the system keyboard layout and change the key according to that.

I have a nordic keyboard so that's why the bottom path upgrade is by default the minus key.

**Comment by Valokoodari** [comment]
The script now uses scan codes instead of characters to send keyboard input to the game.

This should fix the problem but I unfortunately can't test if it actually works.

**Comment by MichaelKoopa** [comment]
It does work with slash bound to path 3 but if minus is bound it does not. Also is there a reason the upgrades are keyboard inputs instead of clicks?

**Comment by Valokoodari** [comment]
Seems like it works just like it should now. As for me it still uses the minus because of the nordic layout where the minus is between the right shift and the period.

With everything possible being done with the keyboard instead of the mouse, changes to the UI shouldn't break the script as easily so that's why the upgrades are done with the keyboard. Also slight differences in the resolution of the game shouldn't affect the script as easily either (for example fullscreen 1080p vs. windowed 1080p which both worked at least when I last tested even though the window border does change the coordinates slightly).

So mostly the keyboard is preferred over the mouse just to save a bit of time when tweaking the script.
