### ISSUE TITLE
[documentation] Map unlocking loop

### ISSUE THREAD

**Issue by gnomechewer** [Valokoodari/btd6-ahk#46]
_README.md: "All expert maps unlocked. (Not sure on this one, but better safe than sorry.)"_
As long as the user has unlocks available, the script will unlock it then proceed as normal. If the user does not have an unlock available, I assume the script will continue clicking the locked map in a loop. I suggest getting images of the "Locked" and "Click to Unlock" text if fixing this case.

**Comment by Valokoodari** [comment]
Because the collection bonus can be on a locked map (as shown in the image below), the script can now be used even during an event without the event type specified to only require one map (Dark Castle by default) to be unlocked.  

However, if the event type has been specified and the bonus in on a locked map, the script will only get stuck if there is no unlock available.

![image](https://user-images.githubusercontent.com/28293838/221185294-ae6d32ef-eece-433a-9c86-6ee17bd0a138.png)
