### ISSUE TITLE
Bloody puddles not working

### ISSUE THREAD

**Issue by danielhits** [Valokoodari/btd6-ahk#74]
I try to use the script and it works on all other maps but not bloody puddles.

**Comment by Valokoodari** [comment]
In which way does it not work (doesn't start the game, ends up in defeat, something else)?
What gets written in the log (by default `logs/log.txt`)?

**Comment by danielhits** [comment]
The script enters bloody puddles but does not put down monkeys or start the bloons

[11:25:09] Script started
[11:25:09] home
[11:25:11] map_selection
[11:25:20] in_game
[11:25:48] Script stopped


[log.txt](https://github.com/Valokoodari/btd6-ahk/files/10838586/log.txt)

**Comment by Valokoodari** [comment]
Please wait a bit longer so that there is either `Map not recognized` or `Map recognized: ...` in the log. The map recognition is unfortunately sometimes quite slow but it will be optimized the next time I have some extra time.

**Comment by danielhits** [comment]
[12:01:03] Script started
[12:01:03] home
[12:01:05] map_selection
[12:01:15] in_game
[12:01:36] Map not recognized
[12:01:56] Map not recognized
[12:02:17] Map not recognized
[12:02:37] Map not recognized
[12:02:57] Map not recognized
[12:03:17] Map not recognized
[12:03:39] Map not recognized
[12:04:12] Script stopped
[log.txt](https://github.com/Valokoodari/btd6-ahk/files/10838954/log.txt)

**Comment by pireneus** [comment]
i fixed it by cutting the image 
![mspaint_lBCmPem3JD](https://user-images.githubusercontent.com/5862713/221589857-77ff4c5c-91d5-41ff-8c15-eff28efe06c7.png)

but there is a nother issue on puddles in this line 
![notepad_eaaCCXVMmR](https://user-images.githubusercontent.com/5862713/221590133-9d965c11-da61-4313-ad06-940811c76b11.png)

it actually places a sticky monkey instead of a sniper
on fullscreen 1080p

**Comment by danielhits** [comment]
when will you add this to main build

**Comment by Valokoodari** [comment]
I should have enough time on Thursday or Friday but for now you could try replacing the image `img/maps/bloody_puddles.png` with a screenshot with the map open cropped so that there are no moving elements in the area. Raindrops moving through the area are okay as long as there aren't multiple at different times and they don't end up in the screenshot. The screenshot should also have enough contrast to not cause problems with other maps so I recommend including at least a small part of the car.

**Comment by Valokoodari** [comment]
The map recognition has been updated.
