### ISSUE TITLE
can this script play deflation?

### ISSUE THREAD

**Issue by szefgg** [Valokoodari/btd6-ahk#83]
I only need exp, so is it possibilty to make this script playing deflation

**Comment by Valokoodari** [comment]
To make the script play deflation you would need to implement the strategy for deflation for at least a single map and then edit the script to choose that map by default (if other than dark castle) and to choose deflation instead of standard as the difficulty.

So it's possible and shouldn't even be too difficult. I don't currently have the time or reason to do that though.
