### ISSUE TITLE
Script optimization + unit exp

### ISSUE THREAD

**Issue by kobisjeruk** [Valokoodari/btd6-ahk#88]
I tweak the script in line with YT's fenixkillah collection event (not 100% copied, some tweaks are based on my own optimization). I also made it so you can set (in config) if you want to add a unit, say beast handler or glue gunner (least exp unit for me personally) and so far I manage to gain 4.8mil exp on beast handler using this (doubled glue gunner exp which I have had since the beginning).
It is not 100% optimized. There are always rooms for improvement imo. Let me know if you are interested.
[btd6-ahk-main-20230405.zip](https://github.com/Valokoodari/btd6-ahk/files/11184261/btd6-ahk-main-20230405.zip)

**Comment by kobisjeruk** [comment]
For the records I made tweaks to main.ahk (just to change start to Ctrl+Z and stop to Ctrl+X), config.ini (adding 2 var 'expEnabled' and 'expUnit'), config.ahk (linking the 2 vars added in config.ini) and all maps (ravine.ahk, quad.ahk, infernal.ahk etc) and add another script in utils named expunit.ahk
The rest I did not touch/change.

**Comment by Valokoodari** [comment]
Thank you for these changes even though I don't see strategy optimizations as necessary at the moment. The next changes to the strategies, as long as nothing breaks, should be to remove the dependency on monkey knowledge.

And as for the tower exp, I think that this is something to the right direction for the yet unreleased xp-grinder branch that I've been testing live on Twitch for a week now. The implementation for that should however be made simpler and to work for all towers. I do really like your idea to let the user choose which tower to collect exp for as I had only thought about letting the script choose a random tower in every game.

Also please submit any code changes in the future through pull requests instead of a file on an issue as that makes comparing changes a lot easier. Preferably also split different features to separate pull requests.

**Comment by kobisjeruk** [comment]
I whole heartedly agree that 'unit exp' would work better using only 1 map for 1 mode like say deflection on dark castle like you tested on twitch instead of adding it on top of event collection scripts. I was thinking of scripting to allow selection of all (non-hero) towers from dart monkey all the way to banana farm (size wise). 
Secondly I will test 0 monkey knowledge setup for collection event to help newbies with as few parameters as possible (for example maybe hero-less or freely available hero like quincy and only up to tier 3? something like that)
Thirdly, I dont really know how to use github so please forgive my transgression regarding the proper channel/way to submit edit and whatnot. I will figure it out.
p/s: Thanks for fixing the 'defeat' bug/issue. I thought it was only on my end so I didnt say anything because I dont want to be a bother, well more so than I already am.
